// Code generated by "stringer -type Hoge"; DO NOT EDIT.

package main

import "strconv"

const _Hoge_name = "HOGEFUGAMOGA"

var _Hoge_index = [...]uint8{0, 4, 8, 12}

func (i Hoge) String() string {
	if i < 0 || i >= Hoge(len(_Hoge_index)-1) {
		return "Hoge(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hoge_name[_Hoge_index[i]:_Hoge_index[i+1]]
}
