// Code generated by "stringer -type Owner"; DO NOT EDIT.

package main

import "strconv"

const _Owner_name = "DECKPLAYER1PLAYER2PLAYER3PLAYER4PLAYER5PLAYER6ACTION1ACTION2ACTION3ACTION4ACTION5ACTION6IKKISIEGE"

var _Owner_index = [...]uint8{0, 4, 11, 18, 25, 32, 39, 46, 53, 60, 67, 74, 81, 88, 92, 97}

func (i Owner) String() string {
	if i < 0 || i >= Owner(len(_Owner_index)-1) {
		return "Owner(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Owner_name[_Owner_index[i]:_Owner_index[i+1]]
}
